### PR TITLE
Updates logo pic

### PR DESCRIPTION
**Pull request by xijing-zhang**
https://github.com/docker-training/presentations/issues/334

### CODE REVIEW

**Review by gnschenker — CHANGES_REQUESTED** [review]
Have you tested the new logo by building the `training/docker-present` container? This is important since the logo is bigger than the original one. Does it still look?
I tried to build the container image but it failed with an error. We need to make sure it works before we can merge this new icon. 

What I did (on my machine) was first copying the presentations folder into the `docker-present` folder and then try to build the image:

```
$ docker image build -t training/docker-present:test .
```

**Comment by gnschenker** [comment]
@xijing-zhang please also note the problem in the `prompt.sh` script (https://github.com/docker-training/docker-present/blob/master/present/prompt.sh). There the script uses the image with the `dev` tag which is obviously wrong. Your new logo will never be displayed...

**Comment by katieannemills** [comment]
Also note there are two places in that file that hard-code the tag - make sure to update both.

**Comment by xijing-zhang** [comment]
This works now with the updated files; however, the logo covers a bright blue hamburger icon that is still a little visible. Should I look into either shifting the logo or deleting the hamburger icon?

**Comment by gnschenker** [comment]
I'd suggest to remove the hamburger menu

**Comment by gnschenker** [comment]
I would suggest to remove the hamburger menu if it is not too much effort

**Comment by katieannemills** [comment]
LGTM

**Pull request merged**
